<?php

namespace AppBundle\Repository;

/**
 * Activite_AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Activite_AgendaRepository extends \Doctrine\ORM\EntityRepository
{
}
