<?php

namespace AppBundle\Repository;

/**
 * ActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActiviteRepository extends \Doctrine\ORM\EntityRepository
{

    public function findUtilisateursByActivite($idActivite){
        $rows = $this->getEntityManager()
            ->createQuery(
                'SELECT u.username, u.id
                FROM AppBundle:Activite a
                INNER JOIN AppBundle:Activite_Agenda aa WITH aa.idActivite = a.id
                INNER JOIN AppBundle:Utilisateur u WITH u.id = aa.idUtilisateur 
                WHERE a.id = :id
                '
            )->setParameter('id', $idActivite)
            ->getResult();

            
        return $rows;


    }

}
