<?php

namespace AppBundle\Repository;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository extends \Doctrine\ORM\EntityRepository
{


    public function findActivitiesByAgendaId($id){
        $rows = $this->getEntityManager()
            ->createQuery(
                'SELECT DISTINCT act.nom as activite_nom, act.date as date_activite, act.description, act.id
                FROM AppBundle:Agenda a
                INNER JOIN AppBundle:Activite_Agenda aa WITH aa.idAgenda = a.id
                INNER JOIN AppBundle:Activite act WITH act.id = aa.idActivite 
                WHERE a.id = :id
                '
            )->setParameter('id', $id)
            ->getResult();

            
        return $rows;

    }
}
