<?php

namespace AppBundle\Repository;

/**
 * MoneyPotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyPotRepository extends \Doctrine\ORM\EntityRepository
{
}
