<?php

namespace AppBundle\Repository;

/**
 * TransactionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TransactionRepository extends \Doctrine\ORM\EntityRepository
{

    public function findTransactionUser($idMoneyPot){
        $rows = $this->getEntityManager()
            ->createQuery(
                'SELECT u.username, t.dateTransaction, t.valeur
                FROM AppBundle:Transaction t
                INNER JOIN AppBundle:Utilisateur u WITH u.id = t.idUtilisateur
                INNER JOIN AppBundle:MoneyPot mp WITH mp.id = t.idMoneyPot
                WHERE mp.id = :id
                '
            )->setParameter('id', $idMoneyPot)
            ->getResult();

            
        return $rows;


    }
}
