<?php

namespace AppBundle\Repository;

/**
 * Utilisateur_VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Utilisateur_VoyageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByUtilisateurAndVoyage($idUtilisateur, $idVoyage){
        $rows = $this->getEntityManager()
            ->createQuery(
                'SELECT uv.idVoyage, uv.idUtilisateur, uv.isCreator
                FROM AppBundle:Utilisateur_Voyage uv
                WHERE uv.idVoyage = :idVoyage
                AND uv.idUtilisateur = :idUtilisateur
                '
            )->setParameter('idVoyage', $idVoyage)
            ->setParameter('idUtilisateur', $idUtilisateur)
            ->getResult();
        return $rows;

    }

}
